name: Bot de Tareas MichiCasa

on:
  schedule:
    # Minuto 0, Hora 11 UTC (aprox 8 AM Chile)
    # Puedes cambiarlo aqu√≠. Busca "cron calculator" si necesitas otra hora.
    - cron: '0 11 * * *'
  
  # Permite ejecutarlo manualmente desde la pesta√±a "Actions" para probar
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    
    steps:
      - name: üì• Descargar c√≥digo
        uses: actions/checkout@v3

      - name: üêç Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: üì¶ Instalar librer√≠as
        run: pip install -r requirements.txt

      - name: üöÄ Ejecutar Bot
        env:
          # Conectamos las variables con los secretos guardados en GitHub
          API_KEY: ${{ secrets.API_KEY }}
          PHONE_NUMBER: ${{ secrets.PHONE_NUMBER }}
          PHONE_NUMBER_ELLA: ${{ secrets.PHONE_NUMBER_ELLA }}
        run: python main.py
